// Code generated by protoc-gen-go. DO NOT EDIT.
// source: language-agent/JVMMetricsService.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JVMMetrics struct {
	Metrics               []*JVMMetric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ApplicationInstanceId int32        `protobuf:"varint,2,opt,name=applicationInstanceId,proto3" json:"applicationInstanceId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *JVMMetrics) Reset()         { *m = JVMMetrics{} }
func (m *JVMMetrics) String() string { return proto.CompactTextString(m) }
func (*JVMMetrics) ProtoMessage()    {}
func (*JVMMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f947edc73ca4ba, []int{0}
}

func (m *JVMMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JVMMetrics.Unmarshal(m, b)
}
func (m *JVMMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JVMMetrics.Marshal(b, m, deterministic)
}
func (m *JVMMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JVMMetrics.Merge(m, src)
}
func (m *JVMMetrics) XXX_Size() int {
	return xxx_messageInfo_JVMMetrics.Size(m)
}
func (m *JVMMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_JVMMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_JVMMetrics proto.InternalMessageInfo

func (m *JVMMetrics) GetMetrics() []*JVMMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *JVMMetrics) GetApplicationInstanceId() int32 {
	if m != nil {
		return m.ApplicationInstanceId
	}
	return 0
}

func init() {
	proto.RegisterType((*JVMMetrics)(nil), "JVMMetrics")
}

func init() {
	proto.RegisterFile("language-agent/JVMMetricsService.proto", fileDescriptor_84f947edc73ca4ba)
}

var fileDescriptor_84f947edc73ca4ba = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x75, 0x2b, 0x5a, 0xc8, 0x5e, 0x74, 0x51, 0x28, 0x7b, 0xb1, 0x14, 0x95, 0x5e, 0x8c, 0x52,
	0x3d, 0x79, 0x14, 0x2f, 0x15, 0x2a, 0xa5, 0x05, 0x05, 0x6f, 0xd3, 0x38, 0xa4, 0x61, 0x93, 0x4c,
	0x48, 0xa2, 0x4b, 0x7f, 0xc9, 0xaf, 0x94, 0x6d, 0xba, 0x2e, 0xa8, 0x97, 0x30, 0xcc, 0x9b, 0xf7,
	0xf2, 0xde, 0x63, 0x97, 0x1a, 0xac, 0xfc, 0x00, 0x89, 0x57, 0x20, 0xd1, 0xc6, 0xeb, 0xa7, 0x97,
	0xd9, 0x0c, 0xa3, 0x57, 0x22, 0x2c, 0xd1, 0x7f, 0x2a, 0x81, 0xdc, 0x79, 0x8a, 0x54, 0x9e, 0xfd,
	0xba, 0x7b, 0xa4, 0xda, 0x86, 0xe8, 0x11, 0xcc, 0xee, 0xe0, 0x48, 0x90, 0x31, 0x64, 0x1b, 0x81,
	0xb4, 0x19, 0xad, 0x19, 0xeb, 0xd4, 0x8a, 0x73, 0xd6, 0x37, 0x69, 0x1c, 0x64, 0xc3, 0xfd, 0x71,
	0x3e, 0x61, 0xfc, 0x07, 0x5d, 0xb4, 0x50, 0x71, 0xc7, 0x4e, 0xc1, 0x39, 0xad, 0x04, 0x44, 0x45,
	0x76, 0x6a, 0x43, 0x04, 0x2b, 0x70, 0xfa, 0x3e, 0xe8, 0x0d, 0xb3, 0xf1, 0xc1, 0xe2, 0x7f, 0x70,
	0x72, 0xcf, 0x8e, 0xff, 0xf8, 0x2e, 0x2e, 0x58, 0x5f, 0x90, 0xd6, 0x28, 0x62, 0x91, 0x77, 0x5f,
	0x85, 0x32, 0xe7, 0x9d, 0xf7, 0xd1, 0xde, 0x83, 0x64, 0x37, 0xe4, 0x25, 0x07, 0x07, 0x62, 0x8d,
	0x3c, 0x54, 0x9b, 0x1a, 0x74, 0xa5, 0x6c, 0xb3, 0x31, 0xdc, 0x62, 0xac, 0xc9, 0x57, 0xbc, 0x0d,
	0xcf, 0xb7, 0xe1, 0xe7, 0xd9, 0xdb, 0x49, 0x6a, 0x21, 0xbd, 0x6e, 0x95, 0x86, 0xaf, 0x5e, 0xb9,
	0xac, 0x36, 0xaf, 0x3b, 0xfe, 0x73, 0xe2, 0xce, 0x9b, 0x2e, 0x04, 0xe9, 0xd5, 0xe1, 0xb6, 0x95,
	0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x53, 0x04, 0x2c, 0x72, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JVMMetricsServiceClient is the client API for JVMMetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JVMMetricsServiceClient interface {
	Collect(ctx context.Context, in *JVMMetrics, opts ...grpc.CallOption) (*Downstream, error)
}

type jVMMetricsServiceClient struct {
	cc *grpc.ClientConn
}

func NewJVMMetricsServiceClient(cc *grpc.ClientConn) JVMMetricsServiceClient {
	return &jVMMetricsServiceClient{cc}
}

func (c *jVMMetricsServiceClient) Collect(ctx context.Context, in *JVMMetrics, opts ...grpc.CallOption) (*Downstream, error) {
	out := new(Downstream)
	err := c.cc.Invoke(ctx, "/JVMMetricsService/collect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JVMMetricsServiceServer is the server API for JVMMetricsService service.
type JVMMetricsServiceServer interface {
	Collect(context.Context, *JVMMetrics) (*Downstream, error)
}

// UnimplementedJVMMetricsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJVMMetricsServiceServer struct {
}

func (*UnimplementedJVMMetricsServiceServer) Collect(ctx context.Context, req *JVMMetrics) (*Downstream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}

func RegisterJVMMetricsServiceServer(s *grpc.Server, srv JVMMetricsServiceServer) {
	s.RegisterService(&_JVMMetricsService_serviceDesc, srv)
}

func _JVMMetricsService_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JVMMetrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JVMMetricsServiceServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JVMMetricsService/Collect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JVMMetricsServiceServer).Collect(ctx, req.(*JVMMetrics))
	}
	return interceptor(ctx, in, info, handler)
}

var _JVMMetricsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "JVMMetricsService",
	HandlerType: (*JVMMetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "collect",
			Handler:    _JVMMetricsService_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "language-agent/JVMMetricsService.proto",
}
