version: '3'
services:
  skywalking:
    image: apache/skywalking-oap-server:VERSION
    ports:
      - "11800:11800"
      - "12800:12800"
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    ports:
      - "6379:6379"
