// Code generated by protoc-gen-go. DO NOT EDIT.
// source: language-agent/NetworkAddressRegisterService.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkAddresses struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkAddresses) Reset()         { *m = NetworkAddresses{} }
func (m *NetworkAddresses) String() string { return proto.CompactTextString(m) }
func (*NetworkAddresses) ProtoMessage()    {}
func (*NetworkAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e4dbd2bcd5400f, []int{0}
}

func (m *NetworkAddresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkAddresses.Unmarshal(m, b)
}
func (m *NetworkAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkAddresses.Marshal(b, m, deterministic)
}
func (m *NetworkAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAddresses.Merge(m, src)
}
func (m *NetworkAddresses) XXX_Size() int {
	return xxx_messageInfo_NetworkAddresses.Size(m)
}
func (m *NetworkAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAddresses proto.InternalMessageInfo

func (m *NetworkAddresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type NetworkAddressMappings struct {
	AddressIds           []*KeyWithIntegerValue `protobuf:"bytes,1,rep,name=addressIds,proto3" json:"addressIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NetworkAddressMappings) Reset()         { *m = NetworkAddressMappings{} }
func (m *NetworkAddressMappings) String() string { return proto.CompactTextString(m) }
func (*NetworkAddressMappings) ProtoMessage()    {}
func (*NetworkAddressMappings) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4e4dbd2bcd5400f, []int{1}
}

func (m *NetworkAddressMappings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkAddressMappings.Unmarshal(m, b)
}
func (m *NetworkAddressMappings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkAddressMappings.Marshal(b, m, deterministic)
}
func (m *NetworkAddressMappings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkAddressMappings.Merge(m, src)
}
func (m *NetworkAddressMappings) XXX_Size() int {
	return xxx_messageInfo_NetworkAddressMappings.Size(m)
}
func (m *NetworkAddressMappings) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkAddressMappings.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkAddressMappings proto.InternalMessageInfo

func (m *NetworkAddressMappings) GetAddressIds() []*KeyWithIntegerValue {
	if m != nil {
		return m.AddressIds
	}
	return nil
}

func init() {
	proto.RegisterType((*NetworkAddresses)(nil), "NetworkAddresses")
	proto.RegisterType((*NetworkAddressMappings)(nil), "NetworkAddressMappings")
}

func init() {
	proto.RegisterFile("language-agent/NetworkAddressRegisterService.proto", fileDescriptor_a4e4dbd2bcd5400f)
}

var fileDescriptor_a4e4dbd2bcd5400f = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xad, 0x82, 0x90, 0x11, 0x41, 0x83, 0xa8, 0x04, 0x05, 0xc9, 0xa9, 0x17, 0xa7, 0x25,
	0x8a, 0x37, 0x0f, 0x7a, 0x2b, 0x62, 0x29, 0x29, 0x58, 0x10, 0x11, 0x26, 0xc9, 0xb0, 0x09, 0x89,
	0xbb, 0xcb, 0xee, 0xd6, 0x92, 0x57, 0xf2, 0x29, 0xa5, 0x69, 0x82, 0xb6, 0x94, 0x1e, 0xe7, 0xe7,
	0xff, 0x76, 0x66, 0x3f, 0x88, 0x2a, 0x92, 0x62, 0x4e, 0x82, 0x6f, 0x49, 0xb0, 0x74, 0x83, 0x31,
	0xbb, 0x85, 0x32, 0xe5, 0x53, 0x96, 0x19, 0xb6, 0x36, 0x66, 0x51, 0x58, 0xc7, 0x66, 0xca, 0xe6,
	0xbb, 0x48, 0x19, 0xb5, 0x51, 0x4e, 0x05, 0xfd, 0x0d, 0xe6, 0x85, 0xeb, 0x59, 0xe1, 0xf2, 0x91,
	0x74, 0x2c, 0xd8, 0xbc, 0x51, 0x35, 0x6f, 0x9b, 0xe1, 0x10, 0x4e, 0xd6, 0x1f, 0x64, 0xeb, 0x5f,
	0x81, 0x47, 0xdd, 0x70, 0xd9, 0xbb, 0x39, 0xe8, 0x7b, 0xf1, 0x5f, 0x10, 0x8e, 0xe1, 0x7c, 0x9d,
	0x78, 0x25, 0xad, 0x0b, 0x29, 0xac, 0x7f, 0x0f, 0xd0, 0xd6, 0x46, 0xd9, 0x0a, 0x3c, 0x8a, 0xce,
	0x70, 0xcb, 0xee, 0xf8, 0x5f, 0x2f, 0xfa, 0x84, 0xeb, 0x9d, 0x5f, 0xf2, 0x1f, 0xe1, 0x38, 0x21,
	0x97, 0xe6, 0x5d, 0xee, 0x9f, 0xe2, 0xe6, 0xc9, 0xc1, 0x05, 0x6e, 0xbf, 0x29, 0xdc, 0x7b, 0xfe,
	0x80, 0xa1, 0x32, 0x02, 0x49, 0x53, 0x9a, 0x33, 0xda, 0xb2, 0x5e, 0x50, 0x55, 0x16, 0x72, 0x99,
	0x7c, 0xa1, 0x5c, 0x51, 0xd8, 0xf9, 0xc2, 0xc6, 0xd7, 0xa4, 0xf7, 0xee, 0xe9, 0xe4, 0x61, 0xd0,
	0x0c, 0x3f, 0xfb, 0xc1, 0xb4, 0xac, 0x67, 0x2d, 0xd4, 0xae, 0x99, 0x2c, 0xe5, 0xa5, 0xaa, 0x4a,
	0x0e, 0x1b, 0x8d, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xac, 0xdb, 0xf4, 0xa6, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkAddressRegisterServiceClient is the client API for NetworkAddressRegisterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkAddressRegisterServiceClient interface {
	BatchRegister(ctx context.Context, in *NetworkAddresses, opts ...grpc.CallOption) (*NetworkAddressMappings, error)
}

type networkAddressRegisterServiceClient struct {
	cc *grpc.ClientConn
}

func NewNetworkAddressRegisterServiceClient(cc *grpc.ClientConn) NetworkAddressRegisterServiceClient {
	return &networkAddressRegisterServiceClient{cc}
}

func (c *networkAddressRegisterServiceClient) BatchRegister(ctx context.Context, in *NetworkAddresses, opts ...grpc.CallOption) (*NetworkAddressMappings, error) {
	out := new(NetworkAddressMappings)
	err := c.cc.Invoke(ctx, "/NetworkAddressRegisterService/batchRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkAddressRegisterServiceServer is the server API for NetworkAddressRegisterService service.
type NetworkAddressRegisterServiceServer interface {
	BatchRegister(context.Context, *NetworkAddresses) (*NetworkAddressMappings, error)
}

// UnimplementedNetworkAddressRegisterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkAddressRegisterServiceServer struct {
}

func (*UnimplementedNetworkAddressRegisterServiceServer) BatchRegister(ctx context.Context, req *NetworkAddresses) (*NetworkAddressMappings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchRegister not implemented")
}

func RegisterNetworkAddressRegisterServiceServer(s *grpc.Server, srv NetworkAddressRegisterServiceServer) {
	s.RegisterService(&_NetworkAddressRegisterService_serviceDesc, srv)
}

func _NetworkAddressRegisterService_BatchRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkAddresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAddressRegisterServiceServer).BatchRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NetworkAddressRegisterService/BatchRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAddressRegisterServiceServer).BatchRegister(ctx, req.(*NetworkAddresses))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkAddressRegisterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NetworkAddressRegisterService",
	HandlerType: (*NetworkAddressRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "batchRegister",
			Handler:    _NetworkAddressRegisterService_BatchRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "language-agent/NetworkAddressRegisterService.proto",
}
