// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/trace-common.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpanType int32

const (
	SpanType_Entry SpanType = 0
	SpanType_Exit  SpanType = 1
	SpanType_Local SpanType = 2
)

var SpanType_name = map[int32]string{
	0: "Entry",
	1: "Exit",
	2: "Local",
}

var SpanType_value = map[string]int32{
	"Entry": 0,
	"Exit":  1,
	"Local": 2,
}

func (x SpanType) String() string {
	return proto.EnumName(SpanType_name, int32(x))
}

func (SpanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5d7d2e503402948, []int{0}
}

type RefType int32

const (
	RefType_CrossProcess RefType = 0
	RefType_CrossThread  RefType = 1
)

var RefType_name = map[int32]string{
	0: "CrossProcess",
	1: "CrossThread",
}

var RefType_value = map[string]int32{
	"CrossProcess": 0,
	"CrossThread":  1,
}

func (x RefType) String() string {
	return proto.EnumName(RefType_name, int32(x))
}

func (RefType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5d7d2e503402948, []int{1}
}

type SpanLayer int32

const (
	SpanLayer_Unknown      SpanLayer = 0
	SpanLayer_Database     SpanLayer = 1
	SpanLayer_RPCFramework SpanLayer = 2
	SpanLayer_Http         SpanLayer = 3
	SpanLayer_MQ           SpanLayer = 4
	SpanLayer_Cache        SpanLayer = 5
)

var SpanLayer_name = map[int32]string{
	0: "Unknown",
	1: "Database",
	2: "RPCFramework",
	3: "Http",
	4: "MQ",
	5: "Cache",
}

var SpanLayer_value = map[string]int32{
	"Unknown":      0,
	"Database":     1,
	"RPCFramework": 2,
	"Http":         3,
	"MQ":           4,
	"Cache":        5,
}

func (x SpanLayer) String() string {
	return proto.EnumName(SpanLayer_name, int32(x))
}

func (SpanLayer) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5d7d2e503402948, []int{2}
}

type UpstreamSegment struct {
	GlobalTraceIds       []*UniqueId `protobuf:"bytes,1,rep,name=globalTraceIds,proto3" json:"globalTraceIds,omitempty"`
	Segment              []byte      `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpstreamSegment) Reset()         { *m = UpstreamSegment{} }
func (m *UpstreamSegment) String() string { return proto.CompactTextString(m) }
func (*UpstreamSegment) ProtoMessage()    {}
func (*UpstreamSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5d7d2e503402948, []int{0}
}

func (m *UpstreamSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamSegment.Unmarshal(m, b)
}
func (m *UpstreamSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamSegment.Marshal(b, m, deterministic)
}
func (m *UpstreamSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamSegment.Merge(m, src)
}
func (m *UpstreamSegment) XXX_Size() int {
	return xxx_messageInfo_UpstreamSegment.Size(m)
}
func (m *UpstreamSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamSegment.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamSegment proto.InternalMessageInfo

func (m *UpstreamSegment) GetGlobalTraceIds() []*UniqueId {
	if m != nil {
		return m.GlobalTraceIds
	}
	return nil
}

func (m *UpstreamSegment) GetSegment() []byte {
	if m != nil {
		return m.Segment
	}
	return nil
}

type UniqueId struct {
	IdParts              []int64  `protobuf:"varint,1,rep,packed,name=idParts,proto3" json:"idParts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniqueId) Reset()         { *m = UniqueId{} }
func (m *UniqueId) String() string { return proto.CompactTextString(m) }
func (*UniqueId) ProtoMessage()    {}
func (*UniqueId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5d7d2e503402948, []int{1}
}

func (m *UniqueId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniqueId.Unmarshal(m, b)
}
func (m *UniqueId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniqueId.Marshal(b, m, deterministic)
}
func (m *UniqueId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniqueId.Merge(m, src)
}
func (m *UniqueId) XXX_Size() int {
	return xxx_messageInfo_UniqueId.Size(m)
}
func (m *UniqueId) XXX_DiscardUnknown() {
	xxx_messageInfo_UniqueId.DiscardUnknown(m)
}

var xxx_messageInfo_UniqueId proto.InternalMessageInfo

func (m *UniqueId) GetIdParts() []int64 {
	if m != nil {
		return m.IdParts
	}
	return nil
}

func init() {
	proto.RegisterEnum("SpanType", SpanType_name, SpanType_value)
	proto.RegisterEnum("RefType", RefType_name, RefType_value)
	proto.RegisterEnum("SpanLayer", SpanLayer_name, SpanLayer_value)
	proto.RegisterType((*UpstreamSegment)(nil), "UpstreamSegment")
	proto.RegisterType((*UniqueId)(nil), "UniqueId")
}

func init() { proto.RegisterFile("common/trace-common.proto", fileDescriptor_f5d7d2e503402948) }

var fileDescriptor_f5d7d2e503402948 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdf, 0xca, 0xd3, 0x40,
	0x10, 0xc5, 0x9b, 0xf4, 0x6b, 0x9b, 0x4e, 0x8b, 0x5d, 0x16, 0x84, 0xea, 0x55, 0x29, 0x5e, 0x94,
	0xa0, 0xa9, 0x7f, 0xc0, 0x07, 0xb0, 0x56, 0x2c, 0x54, 0x89, 0x69, 0x83, 0xe0, 0x85, 0x30, 0x49,
	0xc6, 0x34, 0x24, 0xd9, 0x8d, 0xbb, 0x5b, 0x6a, 0x5e, 0xc9, 0xa7, 0x94, 0x4d, 0xec, 0xcd, 0x77,
	0xb3, 0xcc, 0x39, 0x9c, 0xf3, 0xdb, 0x81, 0x81, 0x67, 0xa9, 0xac, 0x6b, 0x29, 0xb6, 0x46, 0x61,
	0x4a, 0xaf, 0x7a, 0x11, 0x34, 0x4a, 0x1a, 0xb9, 0xfe, 0x09, 0x8b, 0xb8, 0xd1, 0x46, 0x11, 0xd6,
	0x27, 0xca, 0x6b, 0x12, 0x86, 0xbf, 0x81, 0x27, 0x79, 0x25, 0x13, 0xac, 0xce, 0x36, 0x7e, 0xc8,
	0xf4, 0xd2, 0x59, 0x0d, 0x37, 0xb3, 0xb7, 0xd3, 0x20, 0x16, 0xc5, 0xef, 0x2b, 0x1d, 0xb2, 0xe8,
	0x51, 0x80, 0x2f, 0x61, 0xa2, 0xfb, 0xf6, 0xd2, 0x5d, 0x39, 0x9b, 0x79, 0x74, 0x97, 0xeb, 0x17,
	0xe0, 0xdd, 0x5b, 0x36, 0x55, 0x64, 0x21, 0x2a, 0xd3, 0x13, 0x87, 0xd1, 0x5d, 0xfa, 0x3e, 0x78,
	0xa7, 0x06, 0xc5, 0xb9, 0x6d, 0x88, 0x4f, 0x61, 0xb4, 0x17, 0x46, 0xb5, 0x6c, 0xc0, 0x3d, 0x78,
	0xd8, 0xff, 0x29, 0x0c, 0x73, 0xac, 0x79, 0x94, 0x29, 0x56, 0xcc, 0xf5, 0x5f, 0xc2, 0x24, 0xa2,
	0x5f, 0x5d, 0x94, 0xc1, 0x7c, 0xa7, 0xa4, 0xd6, 0xa1, 0x92, 0x29, 0x69, 0xcd, 0x06, 0x7c, 0x01,
	0xb3, 0xce, 0x39, 0x5f, 0x14, 0x61, 0xc6, 0x1c, 0x3f, 0x86, 0xa9, 0x25, 0x1f, 0xb1, 0x25, 0xc5,
	0x67, 0x30, 0x89, 0x45, 0x29, 0xe4, 0x4d, 0xb0, 0x01, 0x9f, 0x83, 0xf7, 0x11, 0x0d, 0x26, 0xa8,
	0x89, 0x39, 0x16, 0x15, 0x85, 0xbb, 0x4f, 0x0a, 0x6b, 0xba, 0x49, 0x55, 0x32, 0xd7, 0x7e, 0xfe,
	0xd9, 0x98, 0x86, 0x0d, 0xf9, 0x18, 0xdc, 0x2f, 0xdf, 0xd8, 0x83, 0x5d, 0x62, 0x87, 0xe9, 0x85,
	0xd8, 0xe8, 0xc3, 0x05, 0x5e, 0x4b, 0x95, 0x07, 0xd8, 0x58, 0x1d, 0xe8, 0xb2, 0xbd, 0x61, 0x55,
	0x16, 0xc2, 0x3a, 0x75, 0x20, 0xc8, 0x58, 0x46, 0x50, 0xa1, 0xc8, 0xaf, 0x98, 0x53, 0x80, 0x39,
	0x09, 0x13, 0x3a, 0x3f, 0x9e, 0x76, 0xc3, 0xb6, 0x7f, 0x9b, 0xe4, 0x7d, 0x3f, 0xfd, 0x75, 0x9f,
	0x9f, 0xca, 0xf6, 0xfb, 0x7f, 0xc0, 0xd7, 0xbe, 0x1c, 0xda, 0xeb, 0xa4, 0xb2, 0x4a, 0xc6, 0xdd,
	0x9d, 0xde, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x67, 0x7f, 0x39, 0xf1, 0xc4, 0x01, 0x00, 0x00,
}
