// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// In most cases, detect point should be `server` or `client`.
// Even in service mesh, this means `server`/`client` side sidecar
// `proxy` is reserved only.
type DetectPoint int32

const (
	DetectPoint_client DetectPoint = 0
	DetectPoint_server DetectPoint = 1
	DetectPoint_proxy  DetectPoint = 2
)

var DetectPoint_name = map[int32]string{
	0: "client",
	1: "server",
	2: "proxy",
}

var DetectPoint_value = map[string]int32{
	"client": 0,
	"server": 1,
	"proxy":  2,
}

func (x DetectPoint) String() string {
	return proto.EnumName(DetectPoint_name, int32(x))
}

func (DetectPoint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

type KeyStringValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyStringValuePair) Reset()         { *m = KeyStringValuePair{} }
func (m *KeyStringValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyStringValuePair) ProtoMessage()    {}
func (*KeyStringValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *KeyStringValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyStringValuePair.Unmarshal(m, b)
}
func (m *KeyStringValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyStringValuePair.Marshal(b, m, deterministic)
}
func (m *KeyStringValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyStringValuePair.Merge(m, src)
}
func (m *KeyStringValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyStringValuePair.Size(m)
}
func (m *KeyStringValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyStringValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyStringValuePair proto.InternalMessageInfo

func (m *KeyStringValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyStringValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyIntValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyIntValuePair) Reset()         { *m = KeyIntValuePair{} }
func (m *KeyIntValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyIntValuePair) ProtoMessage()    {}
func (*KeyIntValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *KeyIntValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyIntValuePair.Unmarshal(m, b)
}
func (m *KeyIntValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyIntValuePair.Marshal(b, m, deterministic)
}
func (m *KeyIntValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyIntValuePair.Merge(m, src)
}
func (m *KeyIntValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyIntValuePair.Size(m)
}
func (m *KeyIntValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyIntValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyIntValuePair proto.InternalMessageInfo

func (m *KeyIntValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyIntValuePair) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CPU struct {
	UsagePercent         float64  `protobuf:"fixed64,2,opt,name=usagePercent,proto3" json:"usagePercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}
func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}
func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}
func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}
func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetUsagePercent() float64 {
	if m != nil {
		return m.UsagePercent
	}
	return 0
}

type Commands struct {
	Commands             []*Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Commands) Reset()         { *m = Commands{} }
func (m *Commands) String() string { return proto.CompactTextString(m) }
func (*Commands) ProtoMessage()    {}
func (*Commands) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *Commands) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commands.Unmarshal(m, b)
}
func (m *Commands) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commands.Marshal(b, m, deterministic)
}
func (m *Commands) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commands.Merge(m, src)
}
func (m *Commands) XXX_Size() int {
	return xxx_messageInfo_Commands.Size(m)
}
func (m *Commands) XXX_DiscardUnknown() {
	xxx_messageInfo_Commands.DiscardUnknown(m)
}

var xxx_messageInfo_Commands proto.InternalMessageInfo

func (m *Commands) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type Command struct {
	Command              string                `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 []*KeyStringValuePair `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{4}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Command) GetArgs() []*KeyStringValuePair {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterEnum("DetectPoint", DetectPoint_name, DetectPoint_value)
	proto.RegisterType((*KeyStringValuePair)(nil), "KeyStringValuePair")
	proto.RegisterType((*KeyIntValuePair)(nil), "KeyIntValuePair")
	proto.RegisterType((*CPU)(nil), "CPU")
	proto.RegisterType((*Commands)(nil), "Commands")
	proto.RegisterType((*Command)(nil), "Command")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x6d, 0xe7, 0xfe, 0xbd, 0x13, 0x2c, 0x99, 0x42, 0xf1, 0x34, 0x8a, 0x60, 0xf5, 0x90,
	0x0d, 0x3d, 0x09, 0x9e, 0x9c, 0x17, 0x99, 0x48, 0xe9, 0x50, 0xc1, 0x93, 0x59, 0x7c, 0xa9, 0xa5,
	0x6d, 0x52, 0xd2, 0x6c, 0x33, 0x5f, 0xc9, 0x4f, 0x29, 0x6d, 0x33, 0x41, 0xbc, 0x78, 0x69, 0x9f,
	0xf7, 0xf7, 0xbc, 0x4f, 0x08, 0x79, 0x60, 0xcc, 0x65, 0x51, 0x48, 0x31, 0x6d, 0x7f, 0xb4, 0x54,
	0x52, 0xcb, 0xe0, 0x06, 0xc8, 0x02, 0xcd, 0x52, 0xab, 0x54, 0x24, 0xcf, 0x2c, 0x5f, 0x63, 0xc4,
	0x52, 0x45, 0x3c, 0xe8, 0x64, 0x68, 0x7c, 0x67, 0xe2, 0x84, 0xc3, 0xb8, 0x96, 0xe4, 0x08, 0xba,
	0x9b, 0xda, 0xf6, 0xdd, 0x86, 0xb5, 0x43, 0x70, 0x0d, 0x87, 0x0b, 0x34, 0xf7, 0x42, 0xff, 0x3b,
	0xda, 0xdd, 0x45, 0xcf, 0xa1, 0x33, 0x8f, 0x9e, 0x48, 0x00, 0x07, 0xeb, 0x8a, 0x25, 0x18, 0xa1,
	0xe2, 0x28, 0x74, 0xb3, 0xe3, 0xc4, 0xbf, 0x58, 0x30, 0x83, 0xc1, 0x5c, 0x16, 0x05, 0x13, 0xef,
	0x15, 0x39, 0x85, 0x01, 0xb7, 0xda, 0x77, 0x26, 0x9d, 0x70, 0x74, 0x39, 0xa0, 0xd6, 0x8c, 0x7f,
	0x9c, 0xe0, 0x01, 0xfa, 0x16, 0x12, 0x1f, 0xfa, 0x16, 0xdb, 0x3b, 0xed, 0x46, 0x72, 0x06, 0xfb,
	0x4c, 0x25, 0x95, 0xef, 0x36, 0xc7, 0x8c, 0xe9, 0xdf, 0x77, 0x88, 0x9b, 0x85, 0x8b, 0x19, 0x8c,
	0xee, 0x50, 0x23, 0xd7, 0x91, 0x4c, 0x85, 0x26, 0x00, 0x3d, 0x9e, 0xa7, 0x28, 0xb4, 0xb7, 0x57,
	0xeb, 0x0a, 0xd5, 0x06, 0x95, 0xe7, 0x90, 0x21, 0x74, 0x4b, 0x25, 0x3f, 0x8d, 0xe7, 0xde, 0xbe,
	0x41, 0x28, 0x55, 0x42, 0x59, 0xc9, 0xf8, 0x07, 0xd2, 0x2a, 0x33, 0x5b, 0x96, 0x67, 0xa9, 0xa8,
	0x49, 0x41, 0x05, 0xea, 0xad, 0x54, 0x19, 0x6d, 0x7b, 0x88, 0x9c, 0xd7, 0x63, 0x96, 0xa0, 0xd0,
	0xd3, 0xf6, 0x5b, 0xae, 0x6c, 0x41, 0x5f, 0xee, 0xc9, 0x32, 0x33, 0x2f, 0x36, 0xf8, 0xd8, 0x86,
	0xa2, 0xba, 0x34, 0x2e, 0xf3, 0x55, 0xaf, 0xa9, 0xef, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0x56, 0xa0, 0x7e, 0xd5, 0x01, 0x00, 0x00,
}
